### ISSUE TITLE
Add licensing information

### ISSUE THREAD

**Issue by MrWong99** [IBM/fluent-forward-go#11]
Hi guys, fellow dev from Germany here 👋🏻 
First of all thanks for this awesome project, I was just looking for something like this and the only other example I found was 6 years old...

What is your opinion about importing this code in other software? How do you intend the licensing for this project to be?
I would be very happy if you go (no pun intended) open source and since we would use this in our company also support the development where I can 😄

Have a nice weekend!

**Comment by ScarletTanager** [comment]
Hi @MrWong99 , we're certainly glad to hear of your interest.  I've added the missing license file - we're using an MIT license, so hopefully that works for you.

We would definitely welcome further input (and contributions, if you have them), thanks!

**Comment by MrWong99** [comment]
Works perfectly and thanks to you!
