### ISSUE TITLE
Upgrade ginkgo to v2

### ISSUE THREAD

**Issue by Christopher-Wolf-ibm** [IBM/fluent-forward-go#47]
The version of ginkgo used by this service is out of date.  This needs to be updated to v2.2.0

**Comment by jchauvin** [comment]
@Christopher-Wolf-ibm  and I were running into travis issues through the day that we were trying to correct.  

We have PR - https://github.com/IBM/fluent-forward-go/pull/51 open to update 
- Update golang to 1.18
- Update ginkgo to v2.2
- Fix linting and formatting errors
- update travis image to newer linux to fix linter false positives

We had issues where  the ubuntu version and its stdlib.h appeared to be causing typecheck to cause issues when running golangci-lint, so we updated off that default to the `focal` distribution.

**Comment by Christopher-Wolf-ibm** [comment]
Resolved with PR: https://github.com/IBM/fluent-forward-go/pull/51
