### ISSUE TITLE
SharedKeyHexDigest should be read as Str

### ISSUE THREAD

**Issue by vanonox** [IBM/fluent-forward-go#55]
hi
i have an issue when using shared key
the SharedKeyHexDigest seems to be decoded as bin ( in *Pong DecodeMsg )
but the PONG message returns it as a string ( as the protocol specify ) 

after modifying the code to read as string
it works fine

**Comment by ScarletTanager** [comment]
@vanonox At first glance, it looks like you're right.  If you want to submit a PR with your fix, feel free, otherwise we'll see about fixing it on our end.
