### ISSUE TITLE
WebSocket client get stale connection when server closes the connection

### ISSUE THREAD

**Issue by mirko-lazarevic** [IBM/fluent-forward-go#7]
On branch [add_websocket](https://github.com/IBM/fluent-forward-go/tree/add_websockets)

When the WebSocket server drops an established connection the WebSocket client still can invoke `SendMessage()` without getting an error.

**Comment by mirko-lazarevic** [comment]
The issue is opened by accident. Closing it.

**Comment by BernhardSchmid** [comment]
Had a debug session with @gufranmirza which confirmed that the problem is valid.
